### ISSUE TITLE
Thomas F's review

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-uccs#1]
Lest we forget: https://mailarchive.ietf.org/arch/msg/rats/sxmbwzg5nfyP8m7epGVk8dTUI7M/

Note: although this was a review for birkholz-02, I don't think the points raised have been addressed in birkholz-03 (which I guess it's equivalent to rats-00).

**Comment by cabo** [comment]
Can this be closed now?

**Comment by thomas-fossati** [comment]
Yes.  I have some more comments but I will provide them in another review.
