### ISSUE TITLE
Missing reference to RFC 9165 for .feature CDDL control operator

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-uccs#26]
Appendix A uses .feature for the JC<> generic. That is defined in RFC 9165, not RFC 8610 so a reference to it is needed.

**Comment by cabo** [comment]
Sorry, i fat-fingered the PR...
Please see https://github.com/ietf-rats-wg/draft-ietf-rats-uccs/commit/1be1b5581c9d5054b7f1e9c686c532a0b9a3d4b4
(We didn't have a reference to RFC 8610 either.)
