### ISSUE TITLE
Unsigned JSON format claims?

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-uccs#5]
JWT has this null cipher construct for unsigned JSON claims-sets. It seems wasteful and ill conceived to me especially in light of UCCS.

EAT is successfully defining claims in both JSON and CBOR.

Why not make UCCS in to a CDDL definition of the basic claims in CWT and JWT and define simpler way to do unsigned claims in JSON format?  You already have all the security considerations.

**Comment by cabo** [comment]
I believe the spirit of this issue is now covered in the CDDL.  Closing.
