### ISSUE TITLE
(editorial): harmonize capitalization

### ISSUE THREAD

**Issue by cabo** [ietf-rats-wg/draft-ietf-rats-uccs#8]
(As per Ned Smith's message of November 8, 2022)

**Comment by henkbirkholz** [comment]
Claim Key as specified in RFC8392 are currently called lables in the CDDL in the Appendix. "Claim Key" by itself is only used in the definition of UCCS and never again. Should we decide on a consistent use of Claim Key or highlight that is a synonym to label before the CDDL in appendix?
